version: '3.4'


services:
  # Uncomment any data store you need, or add your own

  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env

  # mysql:
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=sanctions
  #     - MYSQL_USER=sanctions
  #     - MYSQL_PASSWORD=are-fun

  # mongo:
  #   image: mongo
  #   ports:
  #     - 27017:27017
  #   restart: always
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=sanctions
  #     - MONGO_INITDB_ROOT_PASSWORD=are-fun

  api:
    build:
      #context: stubs
      #dockerfile: Dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    #volumes:
    # - ./stubs:/stubs
    # Uncomment links
    links:
      - postgres
    depends_on:
      - postgres
    env_file: 
      - .env

  test:
    build:
      context: smoketest
      dockerfile: Dockerfile
    links:
      - api
    environment:
      - API=api:80
    command:
      - ./run.sh
    volumes:
      - ./smoketest:/smoketest
