version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
  api:
    build:
      #context: stubs
      #dockerfile: Dockerfile
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    env_file: 
      - .env
    restart: always
     #volumes:
    # - ./stubs:/stubs
    # Uncomment links

  test:
    build:
      context: smoketest
      dockerfile: Dockerfile
    links:
      - api
    environment:
      - API=api:8080
    command:
      - ./run.sh
    volumes:
      - ./smoketest:/smoketest
