version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    env_file: 
      - .env
    restart: always
  api_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - $PWD:/go/src/github.com/carrpet/sigma-ratings
  test:
    build:
      context: smoketest
      dockerfile: Dockerfile
    links:
      - api
    environment:
      - API=api:8080
    command:
      - ./run.sh
    volumes:
      - ./smoketest:/smoketest
